namespace mialco.shopping.connector.EbayFeed.EbayClasses
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelDetailsType
    {

        private string channelIDField;

        private ChannelDetailsTypePricingDetails pricingDetailsField;

        /// <remarks/>
        public string channelID
        {
            get
            {
                return this.channelIDField;
            }
            set
            {
                this.channelIDField = value;
            }
        }

        /// <remarks/>
        public ChannelDetailsTypePricingDetails pricingDetails
        {
            get
            {
                return this.pricingDetailsField;
            }
            set
            {
                this.pricingDetailsField = value;
            }
        }
    }

 






 

 
 




 

 
}
