namespace mialco.shopping.connector.EbayFeed.EbayClasses
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InventoryType
    {

        private string sKUField;

        private int totalShipToHomeQuantityField;

        private bool totalShipToHomeQuantityFieldSpecified;

        private ChannelDetailsType[] channelDetailsField;

        /// <remarks/>
        public string SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }

        /// <remarks/>
        public int totalShipToHomeQuantity
        {
            get
            {
                return this.totalShipToHomeQuantityField;
            }
            set
            {
                this.totalShipToHomeQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalShipToHomeQuantitySpecified
        {
            get
            {
                return this.totalShipToHomeQuantityFieldSpecified;
            }
            set
            {
                this.totalShipToHomeQuantityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("channelDetails")]
        public ChannelDetailsType[] channelDetails
        {
            get
            {
                return this.channelDetailsField;
            }
            set
            {
                this.channelDetailsField = value;
            }
        }
    }

 






 

 
 




 

 
}
