//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.Serialization;

namespace mialco.shopping.connector.EbayFeed.EbayClasses
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class productRequest
    {

        private ProductVariationGroupType[] productVariationGroupField;

        private CombinedProductType[] productField;


        private object[] itemsField;

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute("product", typeof(ProductType))]
        ////[System.Xml.Serialization.XmlElementAttribute("productVariationGroup", typeof(ProductVariationGroupType))]
        //public object[] Items
        //{
        //    get
        //    {
        //        return this.itemsField;
        //    }
        //    set
        //    {
        //        this.itemsField = value;
        //    }
        //}

        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("productVariationGroup")]
        //public ProductVariationGroupType[] productVariationGroup
        //{
        //    get
        //    {
        //        return this.productVariationGroupField;
        //    }
        //    set
        //    {
        //        this.productVariationGroupField = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("product")]
        public CombinedProductType[] product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }

    }
}
